### PR TITLE
add post install message

### PR DESCRIPTION
**Pull request by rashmihunt**
As discussed yesterday, added link to follow Post installation steps in https://loopback.io/doc/en/lb3/Installing-the-Oracle-connector.html after a successful installation. @raymondfeng PTAL

### CODE REVIEW

**Comment by rashmihunt** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
I've fixed part of the build failure in CI, but the failure on node 0.12 appears to be related to the use of `require.resolve('.')` at https://github.com/strongloop/loopback-oracle-installer/blob/ea1afbf9289da80ca9e69da50328d2ec4eb298a5/pkginstall.js#L19

For portability, I believe it should be changed to `require.resolve('./')`.

**Comment by rmg** [comment]
FYI, the change made for compatability in 9628d37 still failed because it uncovered other incompatabilities with older versions of Node. In particular, it appears to be using ES6 string methods that don't exist in Node 0.10 and 0.12. They should either be fixed or this module marked as only working with Node v4 or newer.

**Pull request merged**
